config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :pockets
  resources :payments
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def new #untuk menampilkan form data baru
        @teacher = Teacher.new
    end

    def create #untuk memproses data baru yang dimasukan di form new
        teacher = Teacher.new(resource_params)
        teacher.save
        flash[:notice] = 'Teacher has been created'
        redirect_to teachers_path
    end

    def edit #menampilkan data yang sudah disimpan di edit
        @teacher = Teacher.find(params[:id])
    end

    def update #melakukan proses ketika user mengedit data
        @teacher = Teacher.find(params[:id])
        @teacher.update(resource_params)
        flash[:notice] = 'Teacher has been updated'
        redirect_to teacher_path(@teacher)
    end

    def destroy #unuk menghapus data
        @teacher = Teacher.find(params[:id])
        @teacher.destroy
        flash[:notice] = 'Teacher has been deleted'
        redirect_to teachers_path
    end

    def index #menampilkan seluruh data yang ada di database
        @teachers = Teacher.all
    end

    def show #menampilkan sebuah data secara detail
        id = params[:id]
        @teacher = Teacher.find(id)
    end

    private
    def resource_params
        params.require(:teacher).permit(:NIK, :name, :age, :kelas, :mapel)
    end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="card text-white bg-dark mb-10" style="max-width: 275px;">
  <div class="card-body">
    <%= form_for(@teacher) do |t| %>
        <%= t.label :NIK %> </br> 
        <%= t.text_field :NIK %> </br> 

        <%= t.label :name %> </br> 
        <%= t.text_field :name %> </br> 

        <%= t.label :age %> </br> 
        <%= t.text_field :age %> </br>

        <%= t.label :kelas %> </br> 
        <%= t.text_field :kelas %> </br>

        <%= t.label :mapel %> </br> 
        <%= t.text_field :mapel %> </br>

    <br><%= t.submit "Save", class:"btn btn-success" %> 
        <%= link_to 'Back', teachers_path, class:"btn btn-secondary" %> 
    <% end %>
</div>
</div>

app/views/teachers/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>NIK</th>
            <th>Name</th>
            <th>Age</th>
            <th>Kelas</th>
            <th>Mapel</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
    <% @teachers.each do |teacher| %>
    <tr>
        <td><%= teacher.NIK %></td>
        <td><%= teacher.name %></td>
        <td><%= teacher.age %></td>
        <td><%= teacher.kelas %></td>
        <td><%= teacher.mapel %></td>
        <td><%= link_to 'Detail', teacher_path(teacher), class:"btn btn-info" %>  
        <%= link_to 'Edit', edit_teacher_path(teacher), class:"btn btn-warning" %>
        <%= link_to 'Delete', teacher_path(teacher) ,class:"btn btn-danger", method: :delete, data: {confirm: 'Apakah anda yakin?'} %></td>
    </tr>
    <% end %>
    </tbody>
</table> 

&nbsp;<%= link_to 'New teacher', new_teacher_path(), class:"btn btn-success" %>

app/views/teachers/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="card text-white bg-dark mb-10" style="max-width: 275px;">
  <div class="card-body">
        <%= form_for(@teacher) do |s| %>
            <%= s.label :NIK %> </br> 
            <%= s.text_field :NIK %> </br> 

            <%= s.label :name %> </br> 
            <%= s.text_field :name %> </br> 

            <%= s.label :age %> </br> 
            <%= s.text_field :age %> </br>

            <%= s.label :kelas %> </br> 
            <%= s.text_field :kelas %> </br>

            <%= s.label :mapel %> </br> 
            <%= s.text_field :mapel %> </br>
            <br>
            <%= s.submit "Save", class:"btn btn-success" %> 
            <%= link_to 'Back', teachers_path, class:"btn btn-secondary" %>
        
        <% end %>

    </div>
</div>

app/views/teachers/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<div class="col-sm-6">
    <div class="card text-white bg-dark md-6" style="width:200px;">
        <div class="card-header">Teacher</div>
        <div class="card-body">    
            NIK : <%= @teacher.NIK %> </br>
            Name : <%= @teacher.name %> </br>
            Age : <%= @teacher.age %> </br>
            Kelas : <%= @teacher.kelas %> </br>
            Mapel : <%= @teacher.mapel %> </br>
        </div> 
    </div>
        &nbsp;<br><%= link_to 'Back', teachers_path, class:"btn btn-secondary"%>
</div>