config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :pockets
  resources :payments
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new #untuk menampilkan form data baru
        @payment = Payment.new
    end

    def create #untuk memproses data baru yang dimasukan di form new
        payment = Payment.new(resource_params)
        payment.save
        flash[:notice] = 'Payment has been created'
        redirect_to payments_path
    end

    def edit #menampilkan data yang sudah disimpan di edit
        @payment = Payment.find(params[:id])
    end

    def update #melakukan proses ketika user mengedit data
        @payment = Payment.find(params[:id])
        @payment.update(resource_params)
        flash[:notice] = 'Payment has been updated'
        redirect_to payment_path(@payment)
    end

    def destroy #unuk menghapus data
        @payment = Payment.find(params[:id])
        @payment.destroy
        flash[:notice] = 'Payment has been deleted'
        redirect_to payments_path
    end

    def index #menampilkan seluruh data yang ada di database
        @payments = Payment.all
    end

    def show #menampilkan sebuah data secara detail
        id = params[:id]
        @payment = Payment.find(id)
    end

    private
    def resource_params
        params.require(:payment).permit(:transaction_id, :status, :upload)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/edit.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="card text-white bg-dark mb-10" style="max-width: 275px;">
    <div class="card-body">
        <%= form_for(@payment) do |f| %>
            <%= f.label :transaction_id %> </br> 
            <%= f.text_field :transaction_id %> </br> 

            <%= f.label :status%> </br> 
            <%= f.text_field :status%> </br>

            <%= f.label :upload %> </br> 
            <%= f.text_field :upload %> </br>
        <br>
            <%= f.submit "Save",class:"btn btn-success" %> 
            <%= link_to 'Back', payments_path,class:"btn btn-secondary" %> 
            
        <% end %>
    </div>  
</div>

app/views/payments/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Transaction id</th>
        <th>Status</th>
        <th>Upload</th>
        <th>Action</th>

    </tr>
    </thead>
    <tbody>
    <% @payments.each do |r| %>
    <tr>
        <td><%= r.transaction_id %></td>
        <td><%= r.status %></td>
        <td><%= r.upload %></td>
        <td><%= link_to 'Detail', payment_path(r),class:"btn btn-info" %> 
        <%= link_to 'Edit', edit_payment_path(r),class:"btn btn-warning" %> 
        <%= link_to 'Delete', payment_path(r) ,class:"btn btn-danger", method: :delete, data: {confirm: 'Apakah anda yakin?'} %></td>
        
    </tr>
    <% end %>
    </tbody>
</table> 

&nbsp;<%= link_to 'New payment', new_payment_path(),class:"btn btn-success" %>

app/views/payments/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="card text-white bg-dark mb-10" style="max-width: 275px;">
  <div class="card-body">
<%= form_for(@payment) do |s| %>
    <%= s.label :transaction_id %> </br> 
    <%= s.text_field :transaction_id %> </br> 

    <%= s.label :status %> </br> 
    <%= s.text_field :status %> </br>

    <%= s.label :upload %> </br> 
    <%= s.text_field :upload %> </br>
    <br>
    <%= s.submit "Save",class:"btn btn-success" %>
    <%= link_to 'Back', payments_path, class:"btn btn-secondary" %> 

<% end %>
    </div>
</div>

app/views/payments/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<div class="card text-white bg-dark mb-3" style="width:200px; height:250px; left:10px;">
    <div class="card-header">Payment</div>
    <div class="card-body">
        Transaction_id : <%= @payment.transaction_id %> </br>
        Status : <%= @payment.status %> </br>
        Upload : <%= @payment.upload %> </br>
    </div>
</div>
&nbsp;&nbsp;<%= link_to 'Back', payments_path(),class:"btn btn-secondary" %>