config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :pockets
  resources :payments
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    def new #untuk menampilkan form data baru
        @exam = Exam.new
    end

    def create #untuk memproses data baru yang dimasukan di form new
        exam = Exam.new(resource_params)
        exam.save
        flash[:notice] = 'Exam has been created'
        redirect_to exams_path
    end

    def edit #menampilkan data yang sudah disimpan di edit
        @exam = Exam.find(params[:id])
    end

    def update #melakukan proses ketika user mengedit data
        @exam = Exam.find(params[:id])
        @exam.update(resource_params)
        flash[:notice] = 'Exam has been updated'
        redirect_to exam_path(@exam)
    end

    def destroy #unuk menghapus data
        @exam = Exam.find(params[:id])
        @exam.destroy
        flash[:notice] = 'Exam has been deleted'
        redirect_to exams_path
    end

    def index #menampilkan seluruh data yang ada di database
        @exams = Exam.all
    end

    def show #menampilkan sebuah data secara detail
        id = params[:id]
        @exam = Exam.find(id)
    end

    private
    def resource_params
        params.require(:exam).permit(:title, :mapel, :duration, :nilai, :status, :level, :student_id)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/edit.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="card text-white bg-dark mb-10" style="max-width: 275px;">
  <div class="card-body">
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br> 
    <%= f.text_field :title %> </br> 

    <%= f.label :mapel %> </br> 
    <%= f.text_field :mapel %> </br> 

    <%= f.label :duration %> </br> 
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br> 
    <%= f.text_field :nilai %> </br>

    <%= f.label :status %> </br> 
    <%= f.text_field :status %> </br>

    <%= f.label :level %> </br> 
    <%= f.text_field :level %> </br>

    <%= f.label :student_id %> </br> 
    <%= f.text_field :student_id %> </br>

<br><%= f.submit "Save", class:"btn btn-success" %> 
    <%= link_to 'Back', exams_path, class:"btn btn-secondary" %>  
<% end %>

</div>
    </div>

app/views/exams/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Title</th>
            <th>Mapel</th>
            <th>Duration</th>
            <th>Nilai</th>
            <th>Status</th>
            <th>Level</th>
            <th>Student Id<th>
            Action
        </tr>
    </thead>
    
    <tbody>
    <% @exams.each do |exam| %>
    <tr>
        <td><%= exam.title %></td>
        <td><%= exam.mapel %></td>
        <td><%= exam.duration %></td>
        <td><%= exam.nilai %></td>
        <td><%= exam.status %></td>
        <td><%= exam.level %></td>
        <td><%= exam.student_id %></td>
        <td><%= link_to 'Detail', exam_path(exam),class:"btn btn-info" %>
        <%= link_to 'Edit', edit_exam_path(exam),class:"btn btn-warning" %>
        <%= link_to 'Delete', exam_path(exam) ,class:"btn btn-danger", method: :delete, data: {confirm: 'Apakah anda yakin?'} %></td>
    </tr>
    <% end %>
    </tbody>
</table> 

&nbsp; <%= link_to 'New exam', new_exam_path(), class:"btn btn-success" %>

app/views/exams/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="card text-white bg-dark mb-10" style="max-width: 275px;">
  <div class="card-body">
    <div class="form-group ">
    <%= form_for(@exam) do |s| %>
        <%= s.label :title %> </br> 
        <%= s.text_field :title %> </br> 

        <%= s.label :mapel %> </br> 
        <%= s.text_field :mapel %> </br> 

        <%= s.label :duration %> </br> 
        <%= s.text_field :duration %> </br>

        <%= s.label :nilai %> </br> 
        <%= s.text_field :nilai %> </br>

        <%= s.label :status %> </br> 
        <%= s.text_field :status %> </br>

        <%= s.label :level %> </br> 
        <%= s.text_field :level %> </br>

        <%= s.label :student_id %> </br> 
        <%= s.text_field :student_id %> </br>

    <br><%= s.submit "Save", class:"btn btn-success" %> 
        <%= link_to 'Back', exams_path, class:"btn btn-secondary" %>
    <% end %>
    </div>
     </div>
        </div>

app/views/exams/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<div class="col-sm-6">
    <div class="card text-white bg-dark md-6" style="width:200px;">
        <div class="card-header">Exam   </div>
            <div class="card-body">
                Title : <%= @exam.title %> </br>
                Mapel : <%= @exam.mapel %> </br>
                Duration : <%= @exam.duration %> </br>
                Nilai : <%= @exam.nilai %> </br>
                Status : <%= @exam.status %> </br>
                level : <%= @exam.level %> </br>
                student_id : <%= @exam.student_id %> </br>
    </div>
        </div>
        <br><%= link_to 'Back', exams_path, class:"btn btn-secondary"%>
             </div>