config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :pockets
  resources :payments
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    def new #untuk menampilkan form data baru
        @report = Report.new
    end

    def create #untuk memproses data baru yang dimasukan di form new
        report = Report.new(resource_params)
        report.save
        flash[:notice] = 'Report has been created'
        redirect_to reports_path
    end

    def edit #menampilkan data yang sudah disimpan di edit
        @report = Report.find(params[:id])
    end

    def update #melakukan proses ketika user mengedit data
        @report = Report.find(params[:id])
        @report.update(resource_params)
        flash[:notice] = 'Report has been updated'
        redirect_to report_path(@report)
    end

    def destroy #unuk menghapus data
        @report = Report.find(params[:id])
        @report.destroy
        flash[:notice] = 'Report has been deleted'
        redirect_to reports_path
    end

    def index #menampilkan seluruh data yang ada di database
        @reports = Report.all
    end

    def show #menampilkan sebuah data secara detail
        id = params[:id]
        @report = Report.find(id)
    end

    private
    def resource_params
        params.require(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id, :date)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/edit.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="card text-white bg-dark mb-10" style="max-width: 275px;">
  <div class="card-body">
<%= form_for(@report) do |f| %>
    <%= f.label :title %> </br> 
    <%= f.text_field :title %> </br> 

    <%= f.label :hasil %> </br> 
    <%= f.text_field :hasil%> </br> 

    <%= f.label :mapel %> </br> 
    <%= f.text_field :mapel %> </br>

    <%= f.label :teacher_id %> </br> 
    <%= f.text_field :teacher_id %> </br>

    <%= f.label :student_id%> </br> 
    <%= f.text_field :student_id%> </br>

     <%= f.label :date %> </br> 
    <%= f.text_field :date %> </br>
    <br>
    <%= f.submit "Save", class:"btn btn-success" %> 
    <%= link_to 'Back', reports_path,class:"btn btn-secondary" %> 

<% end %>
</div>
</div>

app/views/reports/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Title</th>
        <th>Hasil</th>
        <th>Mapel</th>
        <th>Teacher Id</th>
        <th>Student Id</th>
        <th>Date</th>
        <th>Action</th>
    </tr>
    </thead>

    <tbody>
    <% @reports.each do |r| %>
    <tr>
        <td><%= r.title %></td>
        <td><%= r.hasil %></td>
        <td><%= r.mapel %></td>
        <td><%= r.teacher_id %></td>
        <td><%= r.student_id %></td>
        <td><%= r.date %></td>
        <td><%= link_to 'Detail', report_path(r), class:"btn btn-info" %>  
        <%= link_to 'Edit', edit_report_path(r), class:"btn btn-warning" %> 
        <%= link_to 'Delete', report_path(r) ,class:"btn btn-danger", method: :delete, data: {confirm: 'Apakah anda yakin?'} %></td>
        
    </tr>
    <% end%>
    </tbody>
</table> 

&nbsp;<%= link_to 'New report', new_report_path(),class:"btn btn-success" %>

app/views/reports/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="card text-white bg-dark mb-10" style="max-width: 275px;">
  <div class="card-body">
<%= form_for(@report) do |s| %>
    <%= s.label :title %> </br> 
    <%= s.text_field :title %> </br> 

    <%= s.label :hasil %> </br> 
    <%= s.text_field :hasil %> </br> 

    <%= s.label :mapel %> </br> 
    <%= s.text_field :mapel %> </br>

    <%= s.label :teacher_id%> </br> 
    <%= s.text_field :teacher_id %> </br>

    <%= s.label :student_id %></br> 
    <%= s.text_field :student_id %> </br>

    <%= s.label :date %> </br> 
    <%= s.text_field :date %> </br>
    <br>
    <%= s.submit "Save", class:"btn btn-success" %>
    <%= link_to 'Back', reports_path, class:"btn btn-secondary" %>

    <% end %>
 </div>
</div>

app/views/reports/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<div class="col-sm-6">
<div class="card text-white bg-dark md-6" style="width:200px;">
        <div class="card-header">Teacher</div>
        <div class="card-body">
            Title : <%= @report.title %> </br>
            Hasil : <%= @report.hasil %> </br>
            Mapel: <%= @report.mapel %> </br>
            Teacher_id <%= @report.teacher_id %> </br>
            Student_id : <%= @report.student_id %> </br>
            Date : <%= @report.date %> </br>
        </div> 
</div>
    &nbsp;<br><%= link_to 'Back', reports_path, class:"btn btn-secondary"%>
</div   >